# Generated by Django 3.1.3 on 2020-11-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHipets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_formulario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'formulario',
            },
        ),
    ]
