# Generated by Django 3.1.3 on 2020-11-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHipets', '0002_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='file',
            field=models.FileField(upload_to='pdf/'),
        ),
    ]
