# Generated by Django 3.1.3 on 2020-11-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppHipets', '0003_auto_20201119_0710'),
        ('AppHipets', '0003_auto_20201117_2112'),
    ]

    operations = [
    ]
